/**
 * SimilarWeb Halo Effect Connector
 *
 * Pulls website traffic data for a brand domain using the Manus built-in
 * SimilarWeb Data API. This is an ON-DEMAND feature — data is only fetched
 * when the user explicitly triggers it via the "Load Traffic Data" button.
 *
 * GUARDRAILS (shown in UI):
 * - Data is modelled, not measured. Directionally solid for >500K visits/mo.
 * - "Social" channel does not cleanly isolate TikTok creator traffic.
 * - Use for shape and trend, not precise attribution.
 * - Correlation with creator activity is observational, not causal.
 */

import { callDataApi } from "./_core/dataApi";
import type { SimilarWebData } from "../drizzle/schema";

// ─── Date helpers ─────────────────────────────────────────────────────────────

function getDateRange(monthsBack = 6): { startDate: string; endDate: string } {
  const now = new Date();
  // Last complete month
  const endDate = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const startDate = new Date(endDate.getFullYear(), endDate.getMonth() - (monthsBack - 1), 1);
  return {
    startDate: `${startDate.getFullYear()}-${String(startDate.getMonth() + 1).padStart(2, "0")}`,
    endDate: `${endDate.getFullYear()}-${String(endDate.getMonth() + 1).padStart(2, "0")}`,
  };
}

// ─── Confidence tier ──────────────────────────────────────────────────────────

function getConfidenceTier(monthlyVisits: number): {
  tier: "high" | "medium" | "low";
  note: string;
} {
  if (monthlyVisits >= 500_000) {
    return {
      tier: "high",
      note: "High-traffic site — SimilarWeb estimates are directionally reliable.",
    };
  }
  if (monthlyVisits >= 50_000) {
    return {
      tier: "medium",
      note: "Medium-traffic site — estimates are indicative. Use for trend direction, not precise figures.",
    };
  }
  return {
    tier: "low",
    note: "Lower-traffic site — SimilarWeb estimates are noisier here. Treat as directional only.",
  };
}

// ─── Capture gap diagnostic ───────────────────────────────────────────────────

function detectCaptureGap(
  socialPct: number,
  partnershipPct: number,
  andromedaScore: number
): SimilarWebData["captureGap"] {
  // High creator/ad activity but low own-site social traffic = demand leaking elsewhere
  const creatorActivityHigh = partnershipPct >= 15 || andromedaScore >= 50;
  const socialTrafficLow = socialPct < 8;
  const socialTrafficMedium = socialPct >= 8 && socialPct < 15;

  // Estimate capture rate: how much of social demand lands on own site
  // (rough heuristic — social traffic share vs. expected for creator-active brands)
  const captureRate = Math.min(100, Math.round((socialPct / 20) * 100));

  if (creatorActivityHigh && socialTrafficLow) {
    return {
      detected: true,
      severity: "high",
      socialTrafficPct: socialPct,
      captureRate,
      diagnosis:
        "High creator and partnership ad activity is not converting to own-site traffic. Demand generated by creators is likely landing on Amazon, Argos, or TikTok Shop rather than the brand's own website.",
      recommendation:
        "Add direct-to-site CTAs in creator briefs, test creator-exclusive discount codes that drive to brand.com, and audit the gap between TikTok Shop GMV and own-site conversion.",
    };
  }

  if (creatorActivityHigh && socialTrafficMedium) {
    return {
      detected: true,
      severity: "medium",
      socialTrafficPct: socialPct,
      captureRate,
      diagnosis:
        "Creator activity is generating some own-site traffic but below the expected level for this level of partnership ad investment. Some demand may be leaking to third-party retail.",
      recommendation:
        "Test creator-led landing pages with brand.com URLs to improve traffic capture from social campaigns.",
    };
  }

  return {
    detected: false,
    severity: "none",
    socialTrafficPct: socialPct,
    captureRate,
    diagnosis: "No significant capture gap detected. Social traffic share is proportionate to creator activity.",
    recommendation: "Continue monitoring the social-to-site conversion ratio as creator activity scales.",
  };
}

// ─── Channel mix merger (desktop + mobile average) ────────────────────────────

function mergeChannelMix(
  desktop: Record<string, number>,
  mobile: Record<string, number>
): SimilarWebData["channelMix"] {
  const avg = (a: number, b: number) => Math.round(((a + b) / 2) * 10) / 10;
  return {
    direct: avg(desktop.direct ?? 0, mobile.direct ?? 0),
    organicSearch: avg(desktop.organicSearch ?? 0, mobile.organicSearch ?? 0),
    paidSearch: avg(desktop.paidSearch ?? 0, mobile.paidSearch ?? 0),
    social: avg(desktop.social ?? 0, mobile.social ?? 0),
    referral: avg(desktop.referral ?? 0, mobile.referral ?? 0),
    display: avg(desktop.display ?? 0, mobile.display ?? 0),
    email: avg(desktop.email ?? 0, mobile.email ?? 0),
  };
}

// ─── Parse SimilarWeb API channel response ────────────────────────────────────

function parseChannelResponse(data: Record<string, unknown>): Record<string, number> {
  // SimilarWeb returns channel data under various key shapes — normalise here
  const channels: Record<string, number> = {
    direct: 0,
    organicSearch: 0,
    paidSearch: 0,
    social: 0,
    referral: 0,
    display: 0,
    email: 0,
  };

  // Try to extract from the response — the API returns an array of monthly objects
  // Each object has channel keys like "Direct", "Organic Search", etc.
  const visits = (data as { visits?: unknown[] }).visits;
  if (Array.isArray(visits) && visits.length > 0) {
    // Average across all months returned
    const totals: Record<string, number> = {};
    let count = 0;
    for (const month of visits as Record<string, unknown>[]) {
      count++;
      for (const [key, val] of Object.entries(month)) {
        if (key === "date") continue;
        const normalised = normaliseChannelKey(key);
        totals[normalised] = (totals[normalised] ?? 0) + (typeof val === "number" ? val : 0);
      }
    }
    if (count > 0) {
      for (const [key, total] of Object.entries(totals)) {
        if (key in channels) {
          channels[key] = Math.round((total / count) * 1000) / 10; // convert to %
        }
      }
    }
  }

  return channels;
}

function normaliseChannelKey(key: string): string {
  const map: Record<string, string> = {
    Direct: "direct",
    "Organic Search": "organicSearch",
    "Paid Search": "paidSearch",
    Social: "social",
    Referrals: "referral",
    Referral: "referral",
    Display: "display",
    "Display Ads": "display",
    Mail: "email",
    Email: "email",
  };
  return map[key] ?? key.toLowerCase().replace(/\s+/g, "");
}

// ─── Parse monthly visit trend ────────────────────────────────────────────────

function parseVisitsTrend(
  data: Record<string, unknown>
): Array<{ month: string; visits: number }> {
  const visits = (data as { visits?: unknown[] }).visits;
  if (!Array.isArray(visits)) return [];
  return visits
    .filter((v): v is Record<string, unknown> => typeof v === "object" && v !== null)
    .map((v) => ({
      month: String(v.date ?? ""),
      visits: typeof v.visits === "number" ? v.visits : 0,
    }))
    .filter((v) => v.month && v.visits > 0);
}

// ─── Main connector ───────────────────────────────────────────────────────────

export interface SimilarWebConnectorOptions {
  domain: string;
  /** Partnership % from the audit — used for capture gap diagnostic */
  partnershipPct?: number;
  /** Andromeda score from the audit — used for capture gap diagnostic */
  andromedaScore?: number;
  /** Competitor domains to compare against */
  competitorDomains?: Array<{ brandName: string; domain: string }>;
}

export async function fetchSimilarWebData(
  options: SimilarWebConnectorOptions
): Promise<SimilarWebData> {
  const { domain, partnershipPct = 0, andromedaScore = 0, competitorDomains = [] } = options;
  const { startDate, endDate } = getDateRange(6);
  const shortRange = getDateRange(3);

  try {
    // Fire all calls in parallel to minimise latency
    const [visitsResult, desktopResult, mobileResult, bounceResult, rankResult] =
      await Promise.allSettled([
        callDataApi("Similarweb/get_visits_total", {
          pathParams: { domain },
          query: { country: "world", granularity: "monthly", start_date: startDate, end_date: endDate },
        }),
        callDataApi("Similarweb/get_traffic_sources_desktop", {
          pathParams: { domain },
          query: { country: "world", granularity: "monthly", start_date: shortRange.startDate, end_date: shortRange.endDate },
        }),
        callDataApi("Similarweb/get_traffic_sources_mobile", {
          pathParams: { domain },
          query: { country: "world", granularity: "monthly", start_date: shortRange.startDate, end_date: shortRange.endDate },
        }),
        callDataApi("Similarweb/get_bounce_rate", {
          pathParams: { domain },
          query: { country: "world", granularity: "monthly", start_date: shortRange.startDate, end_date: shortRange.endDate },
        }),
        callDataApi("Similarweb/get_global_rank", {
          pathParams: { domain },
          query: { start_date: shortRange.startDate, end_date: shortRange.endDate },
        }),
      ]);

    // Extract visit trend
    const visitsTrend =
      visitsResult.status === "fulfilled"
        ? parseVisitsTrend(visitsResult.value as Record<string, unknown>)
        : [];

    const latestMonthlyVisits =
      visitsTrend.length > 0 ? visitsTrend[visitsTrend.length - 1].visits : 0;

    // Extract channel mix
    const desktopChannels =
      desktopResult.status === "fulfilled"
        ? parseChannelResponse(desktopResult.value as Record<string, unknown>)
        : {};
    const mobileChannels =
      mobileResult.status === "fulfilled"
        ? parseChannelResponse(mobileResult.value as Record<string, unknown>)
        : {};
    const channelMix = mergeChannelMix(desktopChannels, mobileChannels);

    // Extract bounce rate
    const bounceData = bounceResult.status === "fulfilled"
      ? (bounceResult.value as Record<string, unknown>)
      : null;
    const bounceRate = bounceData
      ? (() => {
          const visits = (bounceData as { visits?: unknown[] }).visits;
          if (Array.isArray(visits) && visits.length > 0) {
            const last = visits[visits.length - 1] as Record<string, unknown>;
            return typeof last.bounce_rate === "number" ? Math.round(last.bounce_rate * 100) : undefined;
          }
          return undefined;
        })()
      : undefined;

    // Extract global rank
    const rankData = rankResult.status === "fulfilled"
      ? (rankResult.value as Record<string, unknown>)
      : null;
    const globalRank = rankData
      ? (() => {
          const visits = (rankData as { visits?: unknown[] }).visits;
          if (Array.isArray(visits) && visits.length > 0) {
            const last = visits[visits.length - 1] as Record<string, unknown>;
            return typeof last.global_rank === "number" ? last.global_rank : undefined;
          }
          return undefined;
        })()
      : undefined;

    // Build channel mix trend (use desktop as primary, fill missing months with 0)
    const channelMixTrend = visitsTrend.map((v) => ({
      month: v.month,
      ...channelMix, // simplified — use averaged mix for all months
      // In a future iteration, we could fetch per-month channel data
    }));

    // Confidence tier
    const { tier: confidenceTier, note: confidenceNote } = getConfidenceTier(latestMonthlyVisits);

    // Capture gap
    const captureGap = detectCaptureGap(channelMix.social, partnershipPct, andromedaScore);

    // Competitor comparison (fire in parallel, best-effort)
    let competitorComparison: SimilarWebData["competitorComparison"] = undefined;
    if (competitorDomains.length > 0) {
      const compResults = await Promise.allSettled(
        competitorDomains.slice(0, 3).map(async (comp) => {
          const [compVisits, compDesktop] = await Promise.allSettled([
            callDataApi("Similarweb/get_visits_total", {
              pathParams: { domain: comp.domain },
              query: { country: "world", granularity: "monthly", start_date: shortRange.startDate, end_date: shortRange.endDate },
            }),
            callDataApi("Similarweb/get_traffic_sources_desktop", {
              pathParams: { domain: comp.domain },
              query: { country: "world", granularity: "monthly", start_date: shortRange.startDate, end_date: shortRange.endDate },
            }),
          ]);

          const compVisitTrend = compVisits.status === "fulfilled"
            ? parseVisitsTrend(compVisits.value as Record<string, unknown>)
            : [];
          const compLatest = compVisitTrend.length > 0
            ? compVisitTrend[compVisitTrend.length - 1].visits
            : 0;
          const compChannels = compDesktop.status === "fulfilled"
            ? parseChannelResponse(compDesktop.value as Record<string, unknown>)
            : {};

          return {
            brandName: comp.brandName,
            domain: comp.domain,
            latestMonthlyVisits: compLatest,
            socialTrafficPct: compChannels.social ?? 0,
            organicSearchPct: compChannels.organicSearch ?? 0,
          };
        })
      );

      competitorComparison = compResults
        .filter((r): r is PromiseFulfilledResult<NonNullable<SimilarWebData["competitorComparison"]>[0]> => r.status === "fulfilled")
        .map((r) => r.value);
    }

    return {
      domain,
      dataAsOf: new Date().toISOString(),
      isMock: false,
      confidenceTier,
      confidenceNote,
      monthlyVisitsTrend: visitsTrend,
      latestMonthlyVisits,
      globalRank,
      bounceRate,
      channelMix,
      channelMixTrend,
      captureGap,
      competitorComparison,
    };
  } catch (err) {
    console.error("[SimilarWeb] Live API failed, falling back to mock:", err);
    return getMockSimilarWebData(domain, partnershipPct, andromedaScore);
  }
}

// ─── Mock data (Ninja Kitchen UK — ninjahousehold.com) ────────────────────────

export function getMockSimilarWebData(
  domain: string,
  partnershipPct = 8,
  andromedaScore = 42
): SimilarWebData {
  const months = ["2025-11", "2025-12", "2026-01", "2026-02", "2026-03", "2026-04"];

  const monthlyVisitsTrend = [
    { month: "2025-11", visits: 312_000 },
    { month: "2025-12", visits: 428_000 }, // Christmas spike
    { month: "2026-01", visits: 289_000 },
    { month: "2026-02", visits: 274_000 },
    { month: "2026-03", visits: 298_000 },
    { month: "2026-04", visits: 315_000 },
  ];

  // Channel mix — Ninja UK is retail-heavy, so direct + organic dominate
  // Social is low (8%) despite creator activity — classic capture gap
  const channelMixTrend = months.map((month, i) => ({
    month,
    direct: 34 + (i % 3),
    organicSearch: 38 - (i % 2),
    paidSearch: 12 + (i % 2),
    social: 6 + (i % 3),        // Low social — the capture gap
    referral: 5 + (i % 2),
    display: 3,
    email: 2,
  }));

  const channelMix: SimilarWebData["channelMix"] = {
    direct: 35,
    organicSearch: 37,
    paidSearch: 12,
    social: 7,   // Only 7% social despite creator activity
    referral: 5,
    display: 3,
    email: 2,
  };

  const captureGap = detectCaptureGap(channelMix.social, partnershipPct, andromedaScore);

  return {
    domain,
    dataAsOf: new Date().toISOString(),
    isMock: true,
    confidenceTier: "medium",
    confidenceNote:
      "Medium-traffic site (~315K visits/mo) — estimates are indicative. Use for trend direction, not precise figures.",
    monthlyVisitsTrend,
    latestMonthlyVisits: 315_000,
    globalRank: 142_800,
    bounceRate: 54,
    channelMix,
    channelMixTrend,
    captureGap,
    competitorComparison: [
      {
        brandName: "Shark",
        domain: "sharkclean.co.uk",
        latestMonthlyVisits: 487_000,
        socialTrafficPct: 18,
        organicSearchPct: 32,
      },
      {
        brandName: "Tefal",
        domain: "tefal.co.uk",
        latestMonthlyVisits: 198_000,
        socialTrafficPct: 11,
        organicSearchPct: 41,
      },
      {
        brandName: "Kenwood",
        domain: "kenwoodworld.com",
        latestMonthlyVisits: 156_000,
        socialTrafficPct: 9,
        organicSearchPct: 44,
      },
    ],
  };
}
